# netlify.toml
# Configuration file for Netlify deployment

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# The following redirect is intended for use with single-page applications (SPA)
# like React Router. It allows client-side routing to work correctly by
# redirecting all routes to index.html and letting the SPA handle the routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
